<a href="https://colab.research.google.com/github/SyedHuzaifa007/Mnist-Fashion-Image-Classification-Deep-Learning-Model/blob/main/Mnist_Fashion_Deep_Learning_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
from keras.datasets import fashion_mnist
from keras import models
from keras import layers

In [3]:
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [4]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [5]:
len(train_images)

60000

In [6]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

In [7]:
network.compile(optimizer='rmsprop', loss='mse', metrics=['accuracy'])

In [8]:
train_images = train_images.reshape(60000, 28*28)
train_images = train_images.astype('float32')/255
test_images = test_images.reshape(10000, 28*28)
test_images = test_images.astype('float32')/255

In [9]:
from keras.utils import to_categorical
test_labels = to_categorical(test_labels)
train_labels = to_categorical(train_labels)

In [20]:
network.fit(train_images, train_labels, epochs=10, batch_size=300)

Epoch 1/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0050 - accuracy: 0.9685
Epoch 2/10
200/200 [==============================] - 2s 10ms/step - loss: 0.0050 - accuracy: 0.9688
Epoch 3/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0049 - accuracy: 0.9694
Epoch 4/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0049 - accuracy: 0.9699
Epoch 5/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0049 - accuracy: 0.9699
Epoch 6/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0048 - accuracy: 0.9710
Epoch 7/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0049 - accuracy: 0.9704
Epoch 8/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0048 - accuracy: 0.9705
Epoch 9/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0048 - accuracy: 0.9705
Epoch 10/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0047 - accuracy: 0.970

In [21]:
network.predict(test_images)

array([[4.03572100e-14, 3.25265791e-12, 1.38783918e-08, ...,
        5.22063783e-05, 2.29198396e-10, 9.99943614e-01],
       [5.65856125e-15, 2.16629701e-20, 1.00000000e+00, ...,
        1.55928624e-17, 3.08149345e-18, 2.70565129e-22],
       [1.01695703e-12, 1.00000000e+00, 3.67710553e-19, ...,
        0.00000000e+00, 1.60127449e-20, 1.09162874e-35],
       ...,
       [1.41245522e-07, 2.55057682e-26, 9.38375866e-09, ...,
        5.04895627e-17, 9.99999881e-01, 8.36404842e-24],
       [4.81439002e-23, 1.00000000e+00, 1.46407430e-20, ...,
        8.27701027e-26, 2.88440885e-20, 3.53112009e-24],
       [8.06712586e-10, 4.06740509e-11, 3.17255535e-06, ...,
        1.08693459e-03, 7.84640088e-06, 1.02358559e-10]], dtype=float32)

In [22]:
test_accuracy = network.evaluate(test_images, test_labels)
print(f"Test Accuracy: {test_accuracy[1]}")

313/313 [==============================] - 1s 2ms/step - loss: 0.0180 - accuracy: 0.8931
Test Accuracy: 0.8931000232696533


In [24]:
import matplotlib.pyplot as plt
plt.figure()
plt.imshow()
plt.colorbar()
plt.grid(False)
plt.show()
train_images = train_images / 255.0
test_images = test_images / 255.0
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(train_images[i], cmap=plt.cm.binary)
    plt.xlabel(class_names[train_labels[i]])
plt.show()

TypeError: ignored

<Figure size 432x288 with 0 Axes>

In [27]:
 train_labels[5]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)